#!/bin/sh

export PATH=/bin:/sbin
export HOME=/var/home

# Where to mount the real root partition
export NEW_ROOT=/new_root

rescue_shell() {
	echo "Starting the recovery shell ..."
	cat /etc/motd
	exec sh
	exit 0
}

if [ ! -d "$NEW_ROOT" ]; then
	echo "WARNING: trying to remount / RW and create $NEW_ROOT ..."
	mount -u -w / &&
	    mkdir $NEW_ROOT ||
	    rescue_shell
fi

echo "Setting up /var directories ..."
mount_tmpfs tmpfs /var
mkdir /var/db /var/empty /var/home /var/run /var/tmp

echo "Executing additional rc scripts ..."
for rcs in /etc/rc.*; do
	if [ -x "$rcs" ]; then
		. $rcs
	fi
done

# Supported 'vfs.root.realroot' syntax:
#
# (1) local:<fs-type>:<dev-path>[:<mount-opts>]
# (2) crypt:<fs-type>:<dev-path>:<map-name>[:<cryptsetup-opts>[:<mount-opts>]]
# (3) tcplay:<fs-type>:<dev-path>:<map-name>[:<tcplay-opts>[:<mount-opts>]]
#
# lvm:<lvm-opts>:...
# ccd:<ccd-opts>:...
#
# See also initrd(7) man page.

IFS=':'
REAL_ROOT=$(sysctl -n vfs.real_root)
if [ -z "${REAL_ROOT}" ]; then
	echo "ERROR: 'vfs.root.realroot' is not set!"
	rescue_shell
fi
set -- $REAL_ROOT
unset IFS

DTYPE="$1"
echo "Preparing root device ($DTYPE) ..."

# Compatible with the legacy syntax for LVM
DEVPATH="$3"
case "$DEVPATH" in
*vg[0-9]*/lv[0-9]*)
	DTYPE="lvm"
        DOPTS=""
	echo "WARNING: Please update to the new syntax:"
	echo "    vfs.root.realroot='lvm::local:$DEVPATH:...'"
	;;
*)
	DOPTS="$2"
	;;
esac

# To configure root device located on LVM, CCD, etc.
if [ -x "/etc/rcdev_${DTYPE}" ]; then
	. /etc/rcdev_${DTYPE} "$DOPTS" || {
	    echo "ERROR: Failed to prepare root device!"
	    rescue_shell
	}
	shift; shift;
fi

MTYPE="$1"; shift
echo "Mounting real root filesystem ($MTYPE) ..."
if [ -x "/etc/rcmount_${MTYPE}" ]; then
	. /etc/rcmount_${MTYPE} "$@" || {
	    echo "ERROR: Failed to mount root filesystem!"
	    rescue_shell
	}
else
	echo "ERROR: Unsupported root type: $MTYPE!"
	rescue_shell
fi

echo "Cleaning up and umounting /var ..."
rm -rf /var/*
umount /var

echo "Mounting devfs in real root ..."
mount_null /dev $NEW_ROOT/dev
