#!/bin/sh

FSTYPE="$1"
DEVICE="/dev/${2#/dev/}"
MAPPING="$3"
OPTIONS="$4"
MNTOPTS="$5"

echo "Mounting $FSTYPE root filesystem from tcplay volume $DEVICE ..."

tcplay -d $DEVICE -m $MAPPING $OPTIONS || {
    echo "ERROR: Failed to open $DEVICE!"
    return 2
}
MOUNTFROM="/dev/mapper/$MAPPING"
mount -o ro -t $FSTYPE $MNTOPTS $MOUNTFROM $NEW_ROOT || {
    echo "ERROR: Failed to mount $MOUNTFROM!"
    return 3
}
